-----------------------------------------------------------------------------------------
--
-- answers.lua
--
-----------------------------------------------------------------------------------------

local t = {
	{--1
		question="Robert De Niro movies",
		correctAnswers= {
			"Grudge Match",
			"New Year's Eve",
			"Limitless",
			"Little Fockers",
			"Righteous Kill",
			"What Just Happened",
			"Stardust",
			"The Good Shepherd",
			"Hide and Seek",
			"Meet the Fockers",
			"Shark Tale",
			"Godsend",
			"Analyze That",
			"Showtime",
			"The Score",
			"15 Minutes",
			"Meet the Parents",
			"Men of Honor",
			"Flawless",
			"Analyze This",
			"Ronin",
			"Jackie Brown",
			"Wag the Dog",
			"Cop Land",
			"Greetings",
			"The Wedding Party",
			"Sam's Song",
			"Hi, Mom!",
			"Bloody Mama",
			"Jennifer on My Mind",
			"Born to Win",
			"Mean Streets",
			"The Last Tycoon",
			"Taxi Driver",
			"1900",
			"New York, New York",
			"The Deer Hunter",
			"Raging Bull",
			"True Confessions",
			"The King of Comedy",
			"Falling in Love",
			"Brazil",
			"The Mission",
			"The Untouchables",
			"Angel Heart",
			"Midnight Run",
			"We're No Angels",
			"Jacknife",
			"Stanley & Iris",
			"Goodfellas",
			"Awakenings",
			"Guilty by Suspicion",
			"Cape Fear",
			"Backdraft",
			"Night and the City",
			"Mistress",
			"This Boy's Life",
			"Mad Dog and Glory",
			"A Bronx Tale",
			"Heat",
			"Casino",
			"The Fan",
			"Sleepers",
			"Marvin's Room",
		},
		incorrectAnswers= {
			"Shawshank Redemption",
			"The Godfather",
			"The Dark Knight",
			"Pulp Fiction",
			"Schindler's List",
			"12 Angry Men",
			"Fight Club",
			"Inception",
			"Forrest Gump",
			"The Matrix",
			"Seven Samurai",
			"City of God",
			"Se7en",
			"The Usual Suspects",
			"Casablanca",
			"Raiders of the Lost Ark",
			"Life Is Beautiful",
			"Rear Window",
			"American History X",
			"Psycho",
			"City Lights",
			"Saving Private Ryan",
			"Spirited Away",
			"Memento",
			"The Intouchables",
			"Sunset Blvd.",
			"Modern Times",
			"Apocalypse Now",
			"The Pianist",
			"The Green Mile",
			"The Departed",
			"Gladiator",
			"The Dark Knight Rises",
			"Back to the Future",
			"Alien",
			"Django Unchained",
			"The Lives of Others",
			"The Prestige",
			"The Great Dictator",
			"The Shining",
			"Cinema Paradiso",
			"Paths of Glory",
			"American Beauty",
			"North by Northwest",
			"WALL·E",
			"The Lion King",
			"Amélie",
			"Citizen Kane",
			"Aliens",
			"Toy Story 3",
			"Vertigo",
			"M",
			"Das Boot",
			"A Clockwork Orange",
			"Double Indemnity",
			"Oldboy",
			"The Wolf of Wall Street",
			"To Kill a Mockingbird",
			"Princess Mononoke",
			"Reservoir Dogs",
			"Requiem for a Dream",
			"Lawrence of Arabia",
			"Braveheart",
			"Full Metal Jacket",
			"Singin' in the Rain",
			"Bicycle Thieves",
			"The Sting",
			"Amadeus",
			"All About Eve",
			"Rashomon",
			"Snatch.",
			"L.A. Confidential",
			"The Apartment",
			"Some Like It Hot",
			"The Third Man",
			"For a Few Dollars More",
			"A Separation",
			"Inglourious Basterds",
			"Yojimbo",
			"Batman Begins",
			"The Kid",
			"2001: A Space Odyssey",
			"Metropolis",
			"Unforgiven",
			"Chinatown",
			"Toy Story",
			"12 Years a Slave",
			"Die Hard",
			"Up",
			"Downfall",
			"Scarface",
			"The Great Escape",
			"Pan's Labyrinth",
			"On the Waterfront",
			"Like Stars on Earth",
			"The Seventh Seal",
			"The Hunt",
			"Wild Strawberries",
			"3 Idiots",
			"The Elephant Man",
			"The General",
			"Ran",
			"Her",
			"Ikiru",
			"The Gold Rush",
			"Blade Runner",
			"My Neighbor Totoro",
			"Gran Torino",
			"Rebecca",
			"Rush",
			"Good Will Hunting",
			"The Big Lebowski",
			"Rang De Basanti",
			"It Happened One Night",
			"The Secret in Their Eyes",
			"Warrior",
			"Cool Hand Luke",
			"The Maltese Falcon",
			"V for Vendetta",
			"Fargo",
			"Gone with the Wind",
			"Trainspotting",
			"Into the Wild",
			"Howl's Moving Castle",
			"Hotel Rwanda",
			"How to Train Your Dragon",
			"The Sixth Sense",
			"Judgment at Nuremberg",
			"Gravity",
			"Annie Hall",
			"The Thing",
			"Platoon",
			"Dial M for Murder",
			"Sin City",
			"Touch of Evil",
			"Kill Bill: Vol. 1",
			"The Lego Movie",
			"A Beautiful Mind",
			"No Country for Old Men",
			"Diabolique",
			"Mary and Max",
			"Life of Brian",
			"Finding Nemo",
			"Network",
			"The Avengers",
			"The Princess Bride",
			"Amores Perros",
			"The Wizard of Oz",
			"Stand by Me",
			"The Grapes of Wrath",
			"Ben-Hur",
			"The 400 Blows",
			"There Will Be Blood",
			"Million Dollar Baby",
			"Hachi: A Dog's Tale",
			"Incendies",
			"Strangers on a Train",
			"Donnie Darko",
			"The Bourne Ultimatum",
			"High Noon",
			"In the Name of the Father",
			"Persona",
			"Gandhi",
			"Notorious",
			"The King's Speech",
			"Infernal Affairs",
			"Jaws",
			"Fanny and Alexander",
			"Twelve Monkeys",
			"La Strada",
			"The Night of the Hunter",
			"The Terminator",
			"Ip Man",
			"The Big Sleep",
			"Stalker",
			"The Battle of Algiers",
			"Dog Day Afternoon",
			"Groundhog Day",
			"Rocky",
			"La Haine",
			"Barry Lyndon",
			"Before Sunrise",
			"The Graduate",
			"Underground",
			"A Christmas Story",
			"The Hustler",
			"The Celebration",
			"Shutter Island",
			"Stalag 17",
			"Castle in the Sky",
			"Roman Holiday",
			"Monsters, Inc.",
			"Memories of Murder",
			"In the Mood for Love",
			"Swades",
			"Slumdog Millionaire",
			"A Fistful of Dollars",
			"The Help",
			"Elite Squad: The Enemy Within",
			"The Killing",
			"Black Swan",
			"Rope",
			"Three Colors: Red",
			"The Truman Show",
			"La Dolce Vita",
			"Beauty and the Beast",
			"Prisoners",
			"Star Trek",
			"Before Sunset"
		}
	},

}

return t
